package tictactoe_redo1.models;


import tictactoe_redo1.strategies.winningStrategy.WinningStrategy;

import java.util.ArrayList;
import java.util.List;

public class Game {
    private Board board;
    private List<Player> players;
    private List<Move> moves;
    private Player winner;
    private GameState gameState;
    private int nextPlayerMoveIndex;
    private List<WinningStrategy> winningStrategies;


//    Game class constructor should be private - Builder dp as we should not
//directly be able to modify the Game
    private Game(){

    }


    public static GameBuilder builder(){
        return new GameBuilder();
    }

    public Board getBoard() {
        return board;
    }
    public List<Player> getPlayers() {
        return players;
    }
    public List<Move> getMoves() {
        return moves;
    }
    public Player getWinner() {
        return winner;
    }
    public GameState getGameState() {
        return gameState;
    }
    public int getNextPlayerMoveIndex() {
        return nextPlayerMoveIndex;
    }
    public List<WinningStrategy> getWinningStrategies() {
        return winningStrategies;
    }

    public static class GameBuilder{
//        private Board board;
//        replacement for board is size
        private int size;

//        We have commented the above var which we copied
//        as these are not coming from client but are generated by the gameonly

//        private List<Move> moves;
//        private Player winner;
//        private GameState gameState;
//        private int nextPlayerMoveIndex;
        private List<Player> players;
        private List<WinningStrategy> winningStrategies;


//        To avoid null ptr exception
        public GameBuilder(){
            this.size = 0;
            this.players = new ArrayList<>();
            this.winningStrategies = new ArrayList<>();
        }
        public GameBuilder setSizeOfBoard(int size) {
            this.size = size;
            return this;
        }

        public GameBuilder setPlayers(List<Player> players) {
            this.players = players;
            return this;
        }

        public GameBuilder setWinningStrategies(List<WinningStrategy> winningStrategies) {
            this.winningStrategies = winningStrategies;
            return this;
        }

        //    //        For multivalued attributes //Additional INFO
//    public tictactoe.models.Game.GameBuilder addPlayer(tictactoe.models.Player player){
//        this.players.add(player);
//        return this;
//    }
//
//
//    public tictactoe.models.Game.GameBuilder addWinningStrategies(tictactoe.strategies.winningstrategies.WinningStrategy winningStrategy){
//        this.winningStrategies.add(winningStrategy);
//        return this;
//    }
        public Game build(){
            return new Game();
        }
    }
}