package parkinglot;

import parkinglot.controllers.TicketController;
import parkinglot.dtos.IssueTicketRequestDTO;
import parkinglot.dtos.IssueTicketResponseDTO;
import parkinglot.models.VehicleType;
import parkinglot.repositories.GateRepository;
import parkinglot.repositories.ParkingLotRepository;
import parkinglot.repositories.TicketRepository;
import parkinglot.repositories.VehicleRepository;
import parkinglot.services.TicketService;

public class ParkingLotApplication {
    public static void main(String[] args) {
//        TicketController -> TicketService -> PLRepo -> GateRepo
        GateRepository gateRepository = new GateRepository();
        VehicleRepository vehicleRepository = new VehicleRepository();
        TicketRepository ticketRepository = new TicketRepository();;
        ParkingLotRepository parkingLotRepository = new ParkingLotRepository();

        TicketService ticketService = new TicketService(gateRepository,vehicleRepository,ticketRepository,parkingLotRepository);

        System.out.println("Created TicketService: " + ticketService);

        System.out.println("Test findByGate: " + parkingLotRepository.findByGate(null));
        TicketController ticketController = new TicketController(ticketService);

        System.out.println("Application Started at Port 8080");
//        Still here this is auto generated by spring boot
//        Application Context -> Prototype registry pattern to store objects above



        IssueTicketResponseDTO responseDTO = ticketController.issueTicket(getIssueTicketRequestDTO("Abhishek","007"));
        System.out.println(responseDTO);

        IssueTicketResponseDTO responseDTO2 = ticketController.issueTicket(getIssueTicketRequestDTO("BK","001"));
        System.out.println(responseDTO2);



    }
    private static IssueTicketRequestDTO getIssueTicketRequestDTO(String name,String number){
        IssueTicketRequestDTO issueTicketRequestDTO = new IssueTicketRequestDTO();
        issueTicketRequestDTO.setGateId(1L);
        issueTicketRequestDTO.setVehicleNumber(number);
        issueTicketRequestDTO.setVehicleOwnerName(name);
        issueTicketRequestDTO.setVehicleType(VehicleType.TWO_WHEELER);
        return issueTicketRequestDTO;
    }
}
